### ISSUE TITLE
Update submission form to new 2018 Event form

### ISSUE THREAD

**Issue by chrsmrtn0** [CityOfBoston/onebostonday#13]
I copied the previous event forms from 2017, wiped the old data and added them to the new project folder. We'll need to redirect the site to the new form.

**Comment by RobErskine** [comment]
@chrsmrtn0  Can you give us a link to where the new form is?

**Comment by chrsmrtn0** [comment]
@RobErskine 
**Drive Folder:** https://drive.google.com/drive/folders/1yQw69BiSjbm8B49w_V7LtqO3n_QBP-6h
**Form:** https://docs.google.com/forms/d/1or2UBOW2AsCphbT1B9-3qUjRu6i8wQqQDsUFg2VOA6Y
**Results:** https://docs.google.com/spreadsheets/d/1zWY62-xR6sRZrXsWf_uAsLFiZa6VnolPKHN0uwrBc64

**Comment by RobErskine** [comment]
Instead of replacing what is currently there with a new form I have updated the current form and archived all of the previous data. It's honestly more work than it's worth to replace what we currently have with a new form. I have to go through each field and update it with a unique hash and redo validation and stuff. It'll be much easier if we can use the form that's been in use for the last 4 years.

**Form:** https://docs.google.com/forms/d/133vcCX--RFXjyDSjNNLRVpIuqmSD47Adu5nahxnW7nI/edit
**Results:** https://docs.google.com/spreadsheets/d/1vO3-CcMjmAgMpdwM7IGaULCwJY5monJQkfBbJyadMpQ/edit#gid=23074078

@chrsmrtn0 let me know if this is an issue

**Comment by chrsmrtn0** [comment]
Thats makes sense, I'm ok with doing things that way.
