### ISSUE TITLE
Acts of Kindness counter

### ISSUE THREAD

**Issue by jkvill1** [CityOfBoston/onebostonday#35]
Fix counter, check current total, report out to @jkvill1 for timing on the switch.

**Comment by RobErskine** [comment]
This can be updated on line [289 of main.js](https://github.com/CityOfBoston/onebostonday/blob/master/build/js/main.js#L289).

Instead of hardcoding it, ajax the waypoint api and pull in the `data[0]["totalrecords"]` key to get the total number of acts of kindness. As of the time of this comment there are 486.

**Comment by mcclaskiem** [comment]
Is the count supposed to be only approved tweets or is it all uses of the hashtag #OneBostonDay? @jkvill1

**Comment by RobErskine** [comment]
This has been updated on staging. @jkvill1 we're hitting the [Wayin counter API](https://metric.wayin.com/xapi/metric/count?apiKey=103adfe9-a7b9-4824-9916-052f7339d73a&id=campaign:6843:127945::aUT30WCpJSjulXZ4,campaign:6843:127945::aYDVSr2FxLE63wT6) and adding up the twitter + instagram posts and using that as our counter. The number isn't super impressive (yet). Let me know when you want to time this to go live.

**Comment by ChristopherAlberto-SRX** [comment]
Working as intended.
Needs to be pushed to prod.
Update ticker for retweet handled in a separate ticket.
